
// UMA FUNÇÃO SEMPRE IRÁ PROCURAR OS DADOS DE FORA
// AO CONTRÁRIO NÃO SERÁ POSSIVEL, POIS AO
// ESTAR DENTRO, ESTARÁ PROTEGIDA PELO ESCOPO
// ENTRETANTO ELA CONSEGUE PASSAR DE FUNÇÃO
// PARA FUNÇÃO



const nome = 'Iuri'; // AQUI TEMOS UMA VARIAVEL GLOBAL

function falaNome() {
   // const nome = 'Borja'; // AQUI AO CRIAR UMA VAR DENTRO DO ESCOPO E CHAMA-LA COM A OUTRA FUNÇAO LOGO ABAIXO, SERA REPRODUZIDA
    console.log(nome); // AQUI ESTAMOS CHAMANDO A VARIAVEL GLOBAL DENTRO DO ESCOPO DE UMA FUNÇÃO
}


function usaFalaNome() {
    const nome = 'Borja'; // MAS AQUI AO CRIAR UMA VAR DENTRO DO ESCOPO ELA É IGNORADA E CHAMA
    // A DO ESCOPO GLOBAL , const nome = 'Iuri; POIS O MESMO VAR ESTA SENDO CHAMADO NA PRIMEIRA FUNÇÃO
    
    falaNome(); // AQUI ESTOU CHAMANDO A FUNÇÃO DE CIMA NO ESCOPO DESSA
}

usaFalaNome(); // AQUI CHAMO A FUNÇÃO   